chore: add mask icon
DeepSourceCorp/zeal pull request #545
Opened 2023-07-27 11:20 UTC by faraaz-deepsource

Optmized with [SVGOMG](https://jakearchibald.github.io/svgomg/)

2023-07-27 11:31 UTC, james-deepsource requested changes

2023-07-27 11:31 UTC, james-deepsource commented on src/icons/mask.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="lucide lucide-venetian-mask"><p
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="lucide lucide-venetian-mask"><path d="M2 12a5 5 0 0 0 5 5 8 8 0 0 1 5 2 8 8 0 0 1 5-2 5 5 0 0 0 5-5V7h-5a8 8 0 0 0-5 2 8 8 0 0 0-5-2H2Z" stroke="currentColor" stroke-width="2"/><path d="M6 11c1.5 0 3 .5 3 2-2 0-3 0-3-2ZM18 11c-1.5 0-3 .5-3 2 2 0 3 0 3-2Z" stroke="currentColor" stroke-width="2"/></svg>
```

2023-07-27 11:44 UTC, james-deepsource commented on src/icons/mask.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="lucide lucide-venetian-mask"><p
Confirm if the stroke width is required once.

2023-07-28 08:43 UTC, james-deepsource requested changes
Let's get rid of the `stroke-width` attributes; it appears a bit thicker. Also, please ensure to run `yarn build-lib-icons` and commit the changes.

2023-07-28 08:43 UTC, james-deepsource commented on src/icons/mask.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="lucide lucide-venetian-mask"><p
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="lucide lucide-venetian-mask"><path d="M2 12a5 5 0 0 0 5 5 8 8 0 0 1 5 2 8 8 0 0 1 5-2 5 5 0 0 0 5-5V7h-5a8 8 0 0 0-5 2 8 8 0 0 0-5-2H2Z" stroke="currentColor" stroke-width="2"/><path d="M6 11c1.5 0 3 .5 3 2-2 0-3 0-3-2ZM18 11c-1.5 0-3 .5-3 2 2 0 3 0 3-2Z" stroke="currentColor"/></svg>
```

2023-07-28 15:48 UTC, shuvam-deepsource approved these changes

2023-07-31 06:21 UTC, james-deepsource approved these changes

2023-07-31 06:21 UTC, merged